apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eshop
  name: eshop
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop
  strategy:
    type: Recreate
