apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: strapi
  name: strapi
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: strapi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: strapi
    spec:
      containers:
        - env:
            - name: CORS_ORIGIN
              value: "*"
            - name: DATABASE_CLIENT
              value: mysql
            - name: DATABASE_HOST
              value: mysql
            - name: DATABASE_NAME
              value: strapi
            - name: DATABASE_PASSWORD
              value: strapi
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_SSL
              value: "false"
            - name: DATABASE_USERNAME
              value: strapi
          image: strapi/strapi
          name: strapi
          ports:
            - containerPort: 1337
          resources: {}
          volumeMounts:
            - mountPath: /srv/app
              name: strapi-claim0
      restartPolicy: Always
      initContainers:
      - name: api-downloader
        image: amazon/aws-cli
        command: ['sh', '-c', "aws s3 cp --recursive --region us-east-2 s3://isotropic/banner-apis/api/ 
/srv/app/api/"]
        volumeMounts:
        - mountPath: /srv/app/api
          subPath: api
          name: strapi-claim0
      - name: banner-image-downloader
        image: amazon/aws-cli
        command: ['sh', '-c', "aws s3 cp --recursive --region us-east-2 s3://isotropic/banners-uploads/
/srv/app/public/uploads"]
        volumeMounts:
        - mountPath: /srv/app/public/uploads
          subPath: public/uploads
          name: strapi-claim0
      volumes:
        - name: strapi-claim0
          persistentVolumeClaim:
            claimName: strapi-claim0
status: {}
