apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nithya
commonLabels:
  app: eshop
resources:
- service.yaml
- deployment.yaml
- namespace.yaml
configMapGenerator:
- files:
  - config.json
  name: eshop-web-config
