apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
  name: eshop
spec:
  type: NodePort
  ports:
    - port: 80
      name: "80"
      targetPort: 80
      nodePort: 32000
  selector:
    app: eshop
